export const DELETE_STORAGE = 'DELETE_STORAGE';
export const GET_LOCAL_STORAGE = 'GET_LOCAL_STORAGE';
export const GET_VIEW_ACTIONS = 'GET_VIEW_ACTIONS';
export const SET_LOCAL_STORAGE = 'SET_LOCAL_STORAGE';
export const SET_VIEW_ACTIONS = 'SET_VIEW_ACTIONS';